CREATE TABLE API_users (
  id INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(45) NOT NULL,
  lastName VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  password VARCHAR(255) NOT NULL,
  dateCreated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  dateDeleted DATETIME NULL DEFAULT NULL,
  dateUpdated DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  role VARCHAR(45) NOT NULL,
  PRIMARY KEY (id));
  
INSERT INTO API_users(firstName, lastName, email, password, role) VALUES
  ('Juhan', 'Juurikas', 'juhan@juurikas.ee', '$2b$10$.XOfSwy.cbdtSeFoStKv4e2XyQV2m91i8h.4tBPxbGw7LzTpfYXCu', 'Admin'),
  ('Juku', 'Juurikas', 'juku@juurikas.ee', '$2b$10$AkiS2VBzORkDESiXYOc2L.dFgZBykCDAnb5R1F41wp0sSfcPmhl9C', 'User');
  -- Näidiskasutajate parool on "juhan"
  
CREATE TABLE IF NOT EXISTS `API_courses` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`courseName` VARCHAR(45) NOT NULL,
	dateCreated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	dateDeleted DATETIME NULL DEFAULT NULL,
	dateUpdated DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));

INSERT INTO API_courses(courseName) VALUES
  ('Rakendusinformaatika');
  
CREATE TABLE IF NOT EXISTS `API_subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subjectName` VARCHAR(45) NOT NULL,
    dateCreated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	dateDeleted DATETIME NULL DEFAULT NULL,
	dateUpdated DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));

INSERT INTO API_subjects(subjectName) VALUES
  ('Programmeerimine II');
  
  CREATE TABLE IF NOT EXISTS `API_rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` VARCHAR(45) NOT NULL,
    dateCreated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	dateDeleted DATETIME NULL DEFAULT NULL,
	dateUpdated DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`));

INSERT INTO API_rooms(roomNumber) VALUES
  ('205');
